#!/bin/sh

cp dots/.* ~/ & cp -r dots/neomutt ~/.config & cp -r dots/mpv ~/.config &
cp -r dots/newsboat ~/.config & cp -rf scripts ~/ &
cp -r dots/gtk-3.0 ~/.config &

if [ ! -d ~/Media ]; then
    mkdir ~/Media
fi &

if [ ! -d ~/.checklist]; then
    mkdir ~/.checklist
    touch ~/.checklist/curr
fi &

if [ ! -d ~/Media/Wallpapers ]; then
    cp -r Wallpapers ~/Media
else
    cp -r Wallpapers/* ~/Media/Wallpapers
fi &&

doas cp ~/.vimrc /root/

cp -r Wallpapers ~/Media &
cd suckless/dmenu &&  make -j4  && doas make install clean &&
cd ../dwm &&  make -j4  && doas make install clean &&
cd ../slock && make -j4  && doas make install clean &&
cd ../slstatus && make -j4  && doas make install clean &&
cd ../st && make -j4 &&  doas make install clean &&
cd ../tabbed && make -j4  && doas make install clean
